const CASES = {
  dependency: {
    dataUrl: "./data/dependency-environment.json",
    title: "Dependency environment failure",
    summary:
      "Compilation succeeded while repeated test failures point to the dependency or test environment before source rollback.",
    reproduce: [
      "moon run cmd/main inspect . \\",
      "  --log fixtures/logs/vitest-missing-matcher.txt \\",
      "  --build-exit-code 0 \\",
      "  --format json",
    ].join("\n"),
  },
  branch: {
    dataUrl: "./data/unexpected-branch.json",
    title: "Unexpected branch state",
    summary:
      "The repository is valid, but the current branch does not match an explicit task expectation, so this worktree should be verified before accepting results.",
    reproduce: [
      "moon run cmd/main inspect . \\",
      "  --expected-branch __agenttrace_expected_branch__ \\",
      "  --format json",
    ].join("\n"),
  },
  compile: {
    dataUrl: "./data/source-compile-error.json",
    title: "Source compile error",
    summary:
      "The compiler exited unsuccessfully and reported a source-located TypeScript error, so the next check belongs in source code rather than dependency state.",
    reproduce: [
      "moon run cmd/main inspect . \\",
      "  --build-log fixtures/logs/tsc-type-error.txt \\",
      "  --build-exit-code 2 \\",
      "  --format json",
    ].join("\n"),
  },
};

const byId = (id) => document.getElementById(id);

function setText(id, value) {
  byId(id).textContent = value ?? "—";
}

function shortHead(value) {
  if (!value) return "—";
  return value.length > 12 ? value.slice(0, 12) : value;
}

function renderEvidence(items) {
  const list = byId("evidence-list");
  list.replaceChildren();

  items.forEach((evidence, index) => {
    const item = document.createElement("li");
    item.className = "evidence-item";

    const marker = document.createElement("span");
    marker.className = "evidence-index";
    marker.textContent = String(index + 1).padStart(2, "0");

    const body = document.createElement("div");
    const title = document.createElement("strong");
    title.textContent = evidence.message;
    const meta = document.createElement("p");
    meta.textContent = `${evidence.kind} · source: ${evidence.source}`;

    body.append(title, meta);
    item.append(marker, body);
    list.append(item);
  });

  setText("evidence-count", `${items.length} signal${items.length === 1 ? "" : "s"}`);
}

function renderActions(items) {
  const list = byId("suggested-checks");
  list.replaceChildren();

  items.forEach((action) => {
    const item = document.createElement("li");
    item.textContent = action;
    list.append(item);
  });
}

function renderReport(data, meta) {
  const diagnosis = data.diagnoses?.[0];
  if (!diagnosis) throw new Error("Visual Report requires at least one diagnosis");

  setText("diagnosis-title", meta.title);
  setText("diagnosis-summary", meta.summary);
  setText("severity", diagnosis.severity);
  setText("confidence", diagnosis.confidence);
  setText("rule-ids", diagnosis.rule_ids?.join(", ") || "—");

  setText("build-status", data.build?.status || "not supplied");
  setText("build-compiler", data.build?.compiler);
  setText("build-exit", data.build?.exit_code);

  setText("test-status", data.tests?.status || "not supplied");
  setText("failed-suites", data.tests?.failed_suites);
  setText("failed-tests", data.tests?.failed_tests);

  setText("repo-branch", data.repository?.branch);
  setText("repo-head", shortHead(data.repository?.head));
  setText("repo-dirty", String(Boolean(data.repository?.is_dirty)));

  renderEvidence(diagnosis.evidence || []);
  renderActions(diagnosis.suggested_checks || []);

  setText("schema-version", `schema ${data.schema_version || "—"}`);
  setText("reproduce-command", meta.reproduce);

  byId("error-state").hidden = true;
  byId("report").hidden = false;
}

function setActiveCase(caseId) {
  document.querySelectorAll("[data-case]").forEach((button) => {
    const active = button.dataset.case === caseId;
    button.classList.toggle("is-active", active);
    button.setAttribute("aria-pressed", String(active));
  });
}

async function loadCase(caseId, updateUrl = true) {
  const resolvedId = CASES[caseId] ? caseId : "dependency";
  const meta = CASES[resolvedId];

  setActiveCase(resolvedId);
  setText("diagnosis-title", "Loading diagnosis…");
  setText(
    "diagnosis-summary",
    "Reading the structured result generated by AgentTrace.",
  );
  byId("report").hidden = true;
  byId("error-state").hidden = true;

  if (updateUrl) {
    const url = new URL(window.location.href);
    url.searchParams.set("case", resolvedId);
    history.replaceState({}, "", url);
  }

  try {
    const response = await fetch(meta.dataUrl, { cache: "no-store" });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    const data = await response.json();
    renderReport(data, meta);
  } catch (error) {
    console.error(error);
    setText("diagnosis-title", "Visual Report bundle is incomplete");
    setText(
      "diagnosis-summary",
      "The static UI loaded, but its CLI-generated diagnosis JSON is missing or invalid.",
    );
    byId("error-state").hidden = false;
  }
}

function main() {
  document.querySelectorAll("[data-case]").forEach((button) => {
    button.addEventListener("click", () => loadCase(button.dataset.case));
  });

  const requested = new URLSearchParams(window.location.search).get("case");
  loadCase(requested || "dependency", false);
}

main();
